export const PORTFOLIO_BUY_STOCKS = 'PORTFOLIO_BUY_STOCKS';
export const PORTFOLIO_SELL_STOCKS =  'PORTFOLIO_SELL_STOCKS';

export const ON_BUY_STOCKS =  'ON_BUY_STOCKS';
export const ON_SELL_STOCKS =  'ON_SELL_STOCKS';

export const GET_STOCK_PROTFOLIO =  'GET_STOCK_PROTFOLIO';
export const GET_FUND_PROTFOLIO =  'GET_FUND_PROTFOLIO';


